### ISSUE TITLE
Endnotes

### ISSUE THREAD

**Issue by thewchan** [standardebooks/laozi_tao-te-ching_james-legge#2]
In Legge's original text of the Tao Te Ching in the "The Sacred Books of China: The Texts of Taoism" as published there are a lot of annotations (footnotes), would it be of interest for me to add these back into the ebook? I'm already doing something similar to my Legge's translation of the Analects.

Check out the book scan here: https://archive.org/details/sacredbookschin00legggoog/page/n73/mode/2up

**Comment by acabal** [comment]
That would be interesting, but it looks like his notes are at the end of each "chapter" not specific footnotes tied to specific noterefs. How would we approach that?

**Comment by thewchan** [comment]
Perhaps a single noteref at the end of each chapters?

**Comment by thewchan** [comment]
If you think this is a good idea I'll go ahead and fork the repo and start working on it @acabal

**Comment by acabal** [comment]
OK, I think that will work. Go for it!

**Comment by thewchan** [comment]
@acabal Would you like me to retain the Legge romanizations in the endnotes? Or translate those to Pinyin or Wade-Giles? Also, how would like like me to semantize Chinese? Should it be xml:lang="zh" for all forms of Chinese, or should they be different for Chinese characters and romanizations?

**Comment by acabal** [comment]
There are different language tags for Romanizations, like `zh-Latn-wadegile`. You'll have to look it up.

If we transliterated the Romanizations, it would be to Wade-Giles which is what we went with in Sun Tzu. But I don't know if we want do do that or if it's even possible to do a 1:1 transliteration. Thoughts? @irontigran?

**Comment by irontigran** [comment]
As Alex said, there are different tags for Romanizations, but I think I've only seen them for pinyin and Wade-Giles. I suppose `zh-Latn` would do if there isn't a specific one for Legge's.

I wouldn't attempt converting the Romanization myself, if only because the documentation and tooling for the Legge system seem to be lacking. For example, [this tool](https://ctext.org/pinyin.pl?if=en) converts between various romanizations, but doesn't include Legge's system - this seems to hold true for most Romanization converters I've found.

[Wikipedia](https://en.wikipedia.org/wiki/Legge_romanization) seems skeptical as well:

> Comparing words in the Legge system with the same words in Wade–Giles shows that there are often minor but nonsystematic differences, which makes direct correlation of the systems difficult.

All that said, I suspect it's still _possible_, and @thewchan would have the best chance of doing it correctly since he speaks Chinese fluently. But it looks to be a lot of additional effort.

**Comment by thewchan** [comment]
If we do go for the translation from Legge, my approach would be identifying what Chinese words Legge was romanizing, and substitute in the W-G romanization for that instead.

If we do keep the Legge, should we keep all diacritics? Right now I think the text itself does not include them, e.g. Tao -> Tâo?

**Comment by thewchan** [comment]
@acabal and @irontigran , I've found this tool: https://www.chineseconverter.com/en/convert/wade-giles-to-chinese that can reliably translate Chinese characters to Wade-Giles; identifying what Chinese words Legge is referring to in the text with his own romanization is fairly trivial for me as it is either obvious through context or I can refer to the actual Taoteching Chinese texts and commentary. If we do decide to translate all Legge romanizations to Wade-Giles I'm confident that I can do it with little problem; it'll just take time. FWIW, these days Wikipedia and mainstream media uses Pinyin more, especially if we knew the context is explicitly Mandarin. In this case I'm not sure if Legge was translating with Mandarin Chinese in mind, although it is possible. In most cases, written Chinese is dialect agnostic, so it doesn't really matter unless we are specifically translating dialogues. Anyway, just my 2 cents, let me know how you all would like me to proceed. Thanks!

**Comment by irontigran** [comment]
Re: diacritics - I kept all the Wade-Giles diacritics in Sun ~~Tzu~~ Tzǔ :D.

It sounds like you're (justifiably) more confident in your ability to convert between romanizations, which just leaves the "should we do it" question. The latest edition (1.2.0) of the manual says that we prefer Wade-Giles, I assume because Alex codified our decision to keep the notes on Sun Tzu as they were.

However, I don't think we should prefer Wade-Giles. _If_ we prefer any romanization, we should prefer Pinyin, as the most modern and widely used option. My argument for keeping Wade-Giles in Sun Tzu was more along these lines:
1. Recognizability for English speakers - everyone (in the Anglosphere) knows who Sun Tzu is. Most would be momentarily confused when presented with "Sunzi". (Similarly, I suspect more people would recognize the Tao Te Ching, rather than the Daodejing.)
2. I didn't think the effort required to convert the romanization was worth it, since Wade-Giles is still reasonably well-known. (Doesn't apply to Legge's, as it seems to have fallen out of use entirely?)
3. I lean towards leaving the text as it is as a general rule.

Therefore, I think the manual should say either that we prefer Pinyin or that we leave the romanization as is, and I would vote for the latter. (And it follows that I would say that we keep Legge's romanization here.)

**Comment by thewchan** [comment]
@irontigran That sounds entirely reasonable to me! Sorry I must have missed the part in the manual about preferring Wade-Giles. I actually do think we should prefer Pinyin as well IF we set a preference, but I don't actually feel that strongly about it. I'm up for keeping Legge as it is (as well as keeping/adding back in diacritics), we should agree on what tags to use though just to be consistent. 

I've been looking at Wikipeida's manual of style regarding this same discussion we're having, and while they generally go for Pinyin, they do allow for keeping more familiar romanization for proper names that isn't Pinyin (Sun Tzu would be a good example, also the Yangtze rivier is another.) So that's something we can think about as well if we choose to prefer one romanization system over another. 

Ultimately while I do have my preferences I'm not really that married to them, and I'm open to what @irontigran has said above and whatever decision @acabal makes. Thanks!

**Comment by acabal** [comment]
Pinyin is more modern, but we have to think of the work involved in conversion too.

If we have a standard, then it should apply to all works. We would have to go back and alter Sun Tzu. That would probably be a lot of work to take it from W-G to Pinyin and someone would have to commit to it, because otherwise why have a standard?

Conversely if standardized on W-G, then we would only have to update Tao Te Ching which is very short, and Analects which is still under production so the opportunity is still there.

If we produce more Chinese work, there's a good chance it will be a Giles translation so the work will already be done for us. We can say the same about Legge. We can't say that about Pinyin--it will always require extra work, and in the future the SE project may not have a Chinese-speaking expert readily available to do it.

Also, looking at the Wikipedia style article it looks like there are regional and even political differences in Pinyin romanization. Using an older method like W-G, now a historical artifact, sidesteps that problem.

As @irontigran stated, W-G is not unfamiliar to modern readers anyway, so it's not like it's a totally archaic. Wikipedia states that W-G has largely replaced Legge.

Therefore I would lean on standardizing to Wade-Giles if we do so.

Maybe the biggest question is, is readability significantly improved by moving away from Legge? In other words is it worth the work, or is Legge basically good enough?

NB Wikipedia says: "Comparing words in the Legge system with the same words in Wade–Giles shows that there are often minor but nonsystematic differences, which makes direct correlation of the systems difficult. "

**Comment by thewchan** [comment]
@acabal These are excellent points. I guess if I do advocate for moving away from Legge is that there are proper nouns as well as other Chinese words where some reader might be more familiar with it to be have render via W-G or Pinyin, rather than Legge, which I think it is different enough from either of those systems such that some words are not easily recognizable. A good example is actually seen in Taoteching. Its alleged author is generally romanized to Lao Tzu (W-G) or Laozi (Pinyin), however in Legge's text it is Lao-𝔷ze (in case your browser doesn't render it, that's the small franktur z). Similarly, Chuang Tzu (W-G) or Zhuangzi, both probably familiar to most readers reading Taoist writings, is rendered as _K_ uang-𝔷ze (note the italics; Legge differentiate some phonetic symbols with italics, hence "k" and "_k_" refers to different consonants.)

That said, I can also see the value in retaining Legge as part of the original document. Because of how prolific Legge is, even though he's pretty much the only one using this system, a good amount of classical Chinese works translated to English will be using Legge romanization. 

I'm not too worried about the note on Wiki regarding the difficulty of one-to-one translation between W-G and Legge; this is a challenge for all romanization system in all dialects of Chinese; barring from using IPA, some romanization system will conflate certain phonetic sounds while other don't. However, at least for Pinyin and W-G, there exist "official" dictionaries that gives the "correct" romanization for each Chinese words. As long as we can identify what Chinese words are being romanized, we can find the correct corresponding W-G/Pinyin romanization without difficulties.

**Comment by acabal** [comment]
From your examples it looks like Legge is definitely more complicated.

Maybe the best approach is to say that SE is and always was an English-language project, so while we can easily standardize on English style, non-English spelling and transcription is basically out of scope and can remain as-is. We can leave it to the producer's discretion if they want to upgrade from a Legge transliteration, and if they do then we require W-G and not Pinyin for the reasons above.

**Comment by thewchan** [comment]
That sounds very reasonable to me!

So I guess the matter at hand is for this (Taoteching) specific production; what do you prefer @acabal ?

**Comment by acabal** [comment]
I'd say if you want to take on the project, convert both to Wade-Giles and make a note in the long description for readers. I'll update the manual with the above thinking.

**Comment by thewchan** [comment]
Sounds great! Thanks so much for all the input everyone; this will be a very fun project for me!

**Comment by thewchan** [comment]
@acabal I have finished transcribing the endnotes as well as the relevant front matter (preface and intros) and modifying your Tao Te Ching to incorporate these material. However, because there's quite a bit of hand transcribing I think I'll need to extract the epub/azw3 and proofread them that way first. But otherwise you can check out how everything looks at https://github.com/thewchan/laozi_tao-te-ching_james-legge

I'll hold off from making a pull request until I've finished proof-reading, but just wanted to let you know my progress. Thanks!

**Comment by acabal** [comment]
Sounds good!

**Comment by thewchan** [comment]
@acabal I have proofread the book and it is ready to be reviewed. Should I create a pull request or should I hold off from that?

**Comment by acabal** [comment]
Yes, if you're ready for review then create a pull request please.
